# General
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -g base-index 1
set -g pane-base-index 1

bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

source-file ~/.local/share/tmux/statusline.conf


# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'ofirgall/tmux-window-name'


# Initialize TMUX plugin manager
run '~/.tmux/plugins/tpm/tpm'
