"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[ui]
default-command = "status"
diff-formatter = "delta"

[ui.diff]
format = "git"

[user]
name = "Alan Alexander Chung Ma"
email = "alan@chung-ma.com"

[aliases]
rebase-all = ["rebase", "-s", "(::trunk())+ & mutable()", "-d", "trunk()"]

[git]
colocate = false

[snapshot]
auto-update-stale = true

[[--scope]]
--when.repositories = ["~/Projects/cispa"]

[--scope.user]
email = "alan.chung-ma@cispa.de"
